---
# see https://pre-commit.com
exclude: |
  (?x)^(
    .+/package.*.json
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=512']
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.7.0
    hooks:
      - id: cspell

  # see: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.21.0
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: textlint
        name: textlint
        language: node
        types: [file]
        files: \.(txt|md|mdown|markdown)$
        exclude: ^\.claude/
        entry: textlint
        require_serial: false
        additional_dependencies:
          - 'textlint@15.5.2'
          - 'textlint-filter-rule-comments@1.3.0'
          - 'textlint-rule-preset-smarthr@1.37.0'
          - 'textlint-rule-preset-ja-technical-writing@12.0.2'

  - repo: local
    hooks:
      - id: shellcheck
        name: ShellCheck
        language: system
        types: [shell]
        entry: shellcheck

  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.4
    hooks:
      - id: biome-check
        additional_dependencies: ['@biomejs/biome@1.9.4']
        types: [json]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Format YAML files
        types:
          - yaml

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.45.0
    hooks:
      - id: renovate-config-validator
        files: renovate\.json
